In [14]:
import pandas as pd

In [15]:
# read in odhf file
df = pd.read_csv('odhf_v1.csv')

In [16]:
# we see there are no missing values for province
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9039 entries, 0 to 9038
Data columns (total 17 columns):
index                        9039 non-null int64
facility_name                9039 non-null object
source_facility_type         7449 non-null object
odhf_facility_type           9026 non-null object
provider                     9039 non-null object
unit                         3 non-null object
street_no                    7495 non-null object
street_name                  7571 non-null object
postal_code                  8877 non-null object
city                         8934 non-null object
province                     9039 non-null object
source_format_str_address    4626 non-null object
CSDname                      8651 non-null object
CSDuid                       7525 non-null float64
Pruid                        9039 non-null int64
latitude                     7543 non-null float64
longitude                    7543 non-null float64
dtypes: float64(3), int64(2), object(12)
memory usage: 1.2+ MB

,index,facility_name,source_facility_type,odhf_facility_type,provider,unit,street_no,street_name,postal_code,city,province,source_format_str_address,CSDname,CSDuid,Pruid,latitude,longitude
0,1,advanced facial & nasal surgery centre,active acute hospital,Hospitals,Canadian Institute for Health Information,NaN,NaN,NaN,T5M4G5,edmonton,ab,NaN,Edmonton,NaN,48,NaN,NaN
1,2,agecare ó beverly centre glenmore,long term care,Nursing and residential care facilities,Canadian Institute for Health Information,NaN,NaN,NaN,T2V4S1,calgary,ab,NaN,Calgary,NaN,48,NaN,NaN
2,3,agecare ó beverly centre lake midnapore,long term care,Nursing and residential care facilities,Canadian Institute for Health Information,NaN,NaN,NaN,T2X3S3,calgary,ab,NaN,Calgary,NaN,48,NaN,NaN
3,4,agecare ó sagewood seniors community inc,long term care,Nursing and residential care facilities,Canadian Institute for Health Information,NaN,NaN,NaN,T1P0E2,strathmore,ab,NaN,Strathmore,NaN,48,NaN,NaN
4,5,agecare ó seton,long term care,Nursing and residential care facilities,Canadian Institute for Health Information,NaN,NaN,NaN,T3M2M3,calgary,ab,NaN,Calgary,NaN,48,NaN,NaN

In [17]:
# list and count number of unique provinces, OK
df['province'].value_counts()

on    3733
qc    2359
bc    1492
sk     473
ab     331
mb     214
ns     195
nl      96
nb      62
yt      39
pe      35
nt       7
nu       3
Name: province, dtype: int64

In [18]:
# filter df for facilities in ON
df_on = df[df['province'].isin(['on'])]
df_on.info()
df_on.head()

# there are 3 types of ODHF facilities Nursing and residential care facilities, Ambulatory health care services and Hospitals                                   
df_on['odhf_facility_type'].value_counts() 

# there is one duplicate facility name
df_on['facility_name'].nunique()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3733 entries, 2400 to 6132
Data columns (total 17 columns):
index                        3733 non-null int64
facility_name                3733 non-null object
source_facility_type         3705 non-null object
odhf_facility_type           3728 non-null object
provider                     3733 non-null object
unit                         0 non-null object
street_no                    3122 non-null object
street_name                  3154 non-null object
postal_code                  3726 non-null object
city                         3724 non-null object
province                     3733 non-null object
source_format_str_address    271 non-null object
CSDname                      3540 non-null object
CSDuid                       3151 non-null float64
Pruid                        3733 non-null int64
latitude                     3159 non-null float64
longitude                    3159 non-null float64
dtypes: float64(3), int64(2), object(12)
memory usage: 525.0+ KB

3732

In [20]:
df_on.to_csv(r'ohdf_v1_ontario.csv', index = False)